name: Screenshot Updater

on:
  push:
    branches:
      - master

jobs:
  update-screenshot:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: "20" # or 18/22 depending on your Next.js support

      - name: Install dependencies
        run: npm ci

      - name: Build Next.js project
        run: npm run build

      - name: Start Next.js server
        run: |
          nohup npm run start &  # runs on port 3000 by default
          sleep 10

      - name: Install Puppeteer
        run: npm install puppeteer

      - name: Run Puppeteer Screenshot Script
        run: node update-screenshot.js

      - name: Commit screenshot.png
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git pull
          git add screenshot.png
          git diff --cached --quiet && echo "No changes to commit" || git commit -m "Update screenshot from workflow"
          git push
